### PR TITLE
fix dub test

### PR DESCRIPTION
**Pull request by MartinNowak**
- which provides it's own main for tests

### CODE REVIEW

**Comment by mleise** [comment]
Hmm, is there a way to pull this off that works outside of dub, too? I usually don't create my projects around dub and in this case use the "unnittest" build in Mono-D which just sets -unittest and expects a main().
I.e. is there a version(dub) I could use or is it maybe time to remove dummy main()'s from projects for unittest builds because we want to move away from running the program after executing the unittests? In the latter case I'll look into changing the compilation settings in Mono-D so they include the -main flag. You probably have a better idea than me where the ecosystem is moving.

**Comment by MartinNowak** [comment]
There is mainSourceFile for executables in dub, that tells it to ignore this file when testing, but that doesn't seem to work with libraries. Alternatively we can define a unittest configuration with targetType  which dub will pick up for testing.

**Comment by MartinNowak** [comment]
updated

**Comment by mleise** [comment]
My dub version still warns me that "package fast defines no main source file", but it works now, thanks. I'll have an eye on that in the future.

**Pull request merged**
